### ISSUE TITLE
Does not work with cross-realm objects

### ISSUE THREAD

**Issue by joepie91** [sindresorhus/is-plain-obj#11]
Actual usecase: I'm using (a fork of) PEG.js to generate parsers, which are then run in a `vm` instance to make `require`s of JS modules work correctly. Every parse result is subsequently (incorrectly) determined by `is-plain-obj` to *not* be a plain object, even when it was created as an object literal.

Reduced testcase:

```js
"use strict";

const isPlainObj = require("is-plain-obj");
const vm = require("vm");

let vmCode = `
module.exports = function() {
	return { foo: "bar" };
}
`;

let exports_ = {};

let sandbox = {
	exports: exports_,
	module: {
		exports: exports_,
	}
};

let script = new vm.Script(vmCode);
script.runInNewContext(sandbox);
let exportedFunction = sandbox.module.exports;

let plainObject = exportedFunction();
console.log(isPlainObj(plainObject)); // false!
```

Not sure how this can be solved, presumably it's caused by the `null`/`Object.prototype` in each realm being different. Perhaps some sort of string-based check similar to the initial object-ness check might work?

**Comment by sindresorhus** [comment]
Can you check if it works across realms if you revert https://github.com/sindresorhus/is-plain-obj/commit/13acf59b9bac40e1440a455856db605591046cd2 ?

**Comment by ehmicky** [comment]
It does not. In both cases (shorter example):

```js
import { runInNewContext } from 'vm'
console.log(isPlainObj(runInNewContext('({})'))) // false
```

The problem is:
  - `Object.prototype.toString.call(value) === '[object Object]` guarantees that `value` is an object cross-realm, but not necessary a plain object
  - Checking that a value is a plain object by using `Object.prototype` does not work cross-realm, since `Object` is a global variable

The following code works:

```js
export default function isPlainObject(value) {
  if (Object.prototype.toString.call(value) !== '[object Object]') {
    return false;
  }

  const prototype = Object.getPrototypeOf(value);
  return prototype === null || Object.getPrototypeOf(prototype) === null;
}
```

This works cross-realm because `null` is not a global variable but a special keyword:

```js
console.log(vm.runInNewContext('null') === null) // true
```

In almost all cases, the only `prototype` where `prototype.__proto__ === null` is `Object.prototype`. It is fairly hard too to create one:
  - `Object.create(null).__proto__` is `undefined`, nor `null`
  - `class ExampleClass extends null` throws
  - `ExampleClass.prototype` is non-configurable and non-writable

So I believe this should be fairly safe and create almost no false positives in real-life code.

**Comment by sindresorhus** [comment]
Sounds good. PR welcome 👍

**Comment by ehmicky** [comment]
Great! Done in https://github.com/sindresorhus/is-plain-obj/pull/14
