### ISSUE TITLE
Is Object.create({}) a plain object or not ?

### ISSUE THREAD

**Issue by bharathvaj-ganesan** [sindresorhus/is-plain-obj#2]
`isPlainObject(Object.create({}));` returns false. It must be true right? Same for `Object.create(null)` Your module returns True it should be false.

**Comment by sindresorhus** [comment]
Lodash returns the same result:

```js
const _ = require('lodash');
_.isPlainObject(Object.create({}));
//=> false
```

I guess it could make sense to return `true` here, although it's the first time I ever see this done.

Try opening an issue on Lodash instead. You'll probably get a better answer over there.

> Same for Object.create(null) Your module returns True it should be false.

This one is correct. It should return `true`.

**Comment by bharathvaj-ganesan** [comment]
[This module](https://github.com/jonschlinkert/is-plain-object) conflicts with yours. For `Object.create(null)` it returns false. I will checkout on lodash. Thanks.

**Comment by yvele** [comment]
> [This module](https://github.com/jonschlinkert/is-plain-object) conflicts with yours. For `Object.create(null)` it returns false. I will checkout on lodash. Thanks.

Sure but the author of [the module](https://github.com/jonschlinkert/is-plain-object) is thinking about changing this behaviour as described in https://github.com/jonschlinkert/is-plain-object/issues/12

Also, `lodash.isPlainObject` consider `Object.create(null)` to be a plain object.

**Comment by ehmicky** [comment]
## `Object.create(null)`

In general the intent is to use `Object.create(null)` as a plain object, but with the added protection against object prototype pollution. 

The main drawback in using `Object.create(null)` is actually that some libraries do not handle it the same way as `{}`, which is mostly due to libraries checking "is this a (plain) object?" that forget to handle `Object.create(null)` as a special case. 

Therefore, the current behavior of considering `Object.create(null)` is probably better. It is also more consistent with other libraries as pointed out by @yvele.

## `Object.create({})`

This might be somewhat similar to creating a new class instance where `{}` is the prototype. For example, one might do:

```js
const createObject = function(prototype) {
  return () => Object.create(prototype)
}

const inheritedProps = { one: 1 }
const createNewObject = createObject(inheritedProps)
const a = createNewObject()
const b = createNewObject()
inheritedProps.one = 2
console.log(a.one) // 2
console.log(b.one) // 2
```

In that example, the instances behave similarly to class instances with inherited properties. Whether `prototype` is an empty object or not should not change whether those instances are considered plain objects. From that standpoint, `Object.create({})` should probably not be considered a plain object (which is also the current behavior).

I have added https://github.com/sindresorhus/is-plain-obj/pull/13 to test that behavior.

What do you think @sindresorhus?
